name: CI da API Rest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Clonando o repositório
      uses: actions/checkout@v4
      
    - name: Configurando o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Instalando dependências
      run: npm install
      
    - name: Rodando os testes (Jest)
      run: npm test