name: CI da API Rest

on:
  push:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o ambiente Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'

    - name: Instalar as dependências do projeto
      run: npm ci

    - name: Liberar permissao de execucao do Jest no Linux
      run: chmod +x ./node_modules/.bin/jest

    - name: Executar os testes automatizados
      run: npm test