name: CI da API Rest

on:
  push:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o ambiente Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.x' # Atualizado para resolver o aviso amarelo do GitHub

    - name: Instalar as dependências do projeto
      run: npm install

    - name: Executar os testes automatizados
      run: npm test